// <auto-generated />
using FreshHarvestMarket.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FreshHarvestMarket.Migrations
{
    [DbContext(typeof(FreshMarketContext))]
    [Migration("20260227005220_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FreshHarvestMarket.Models.Produce", b =>
                {
                    b.Property<int>("ProduceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProduceId"));

                    b.Property<int>("InventoryTotal")
                        .HasColumnType("int");

                    b.Property<string>("ProduceCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProduceDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProduceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProduceId");

                    b.ToTable("Produce");

                    b.HasData(
                        new
                        {
                            ProduceId = 1,
                            InventoryTotal = 20,
                            ProduceCategory = "Vegetable",
                            ProduceDescription = "Fresh green zucchinis",
                            ProduceName = "Zuccihini",
                            UnitPrice = 1.20m
                        },
                        new
                        {
                            ProduceId = 2,
                            InventoryTotal = 25,
                            ProduceCategory = "Vegetable",
                            ProduceDescription = "Ripe red tomatoes",
                            ProduceName = "Tomatoes",
                            UnitPrice = 2.00m
                        },
                        new
                        {
                            ProduceId = 3,
                            InventoryTotal = 15,
                            ProduceCategory = "Other",
                            ProduceDescription = "Local raw honey",
                            ProduceName = "Honey",
                            UnitPrice = 6.00m
                        },
                        new
                        {
                            ProduceId = 4,
                            InventoryTotal = 18,
                            ProduceCategory = "Fruit",
                            ProduceDescription = "Juicy plums",
                            ProduceName = "Plums",
                            UnitPrice = 2.50m
                        },
                        new
                        {
                            ProduceId = 5,
                            InventoryTotal = 30,
                            ProduceCategory = "Vegetable",
                            ProduceDescription = "Freshly harvested potatoes",
                            ProduceName = "Potatoes",
                            UnitPrice = 1.20m
                        },
                        new
                        {
                            ProduceId = 6,
                            InventoryTotal = 12,
                            ProduceCategory = "Fruit",
                            ProduceDescription = "Sweet blueberries",
                            ProduceName = "Blueberries",
                            UnitPrice = 3.00m
                        },
                        new
                        {
                            ProduceId = 7,
                            InventoryTotal = 20,
                            ProduceCategory = "Vegetable",
                            ProduceDescription = "Fresh sweet corn",
                            ProduceName = "Sweet Corn",
                            UnitPrice = 1.75m
                        },
                        new
                        {
                            ProduceId = 8,
                            InventoryTotal = 15,
                            ProduceCategory = "Vegetable",
                            ProduceDescription = "Green broccoli florets",
                            ProduceName = "Broccoli",
                            UnitPrice = 2.25m
                        },
                        new
                        {
                            ProduceId = 9,
                            InventoryTotal = 40,
                            ProduceCategory = "Vegetable",
                            ProduceDescription = "Fresh garlic bulbs",
                            ProduceName = "Garlic",
                            UnitPrice = 0.80m
                        },
                        new
                        {
                            ProduceId = 10,
                            InventoryTotal = 10,
                            ProduceCategory = "Fruit",
                            ProduceDescription = "Sweet red cherries",
                            ProduceName = "Cherries",
                            UnitPrice = 3.50m
                        },
                        new
                        {
                            ProduceId = 11,
                            InventoryTotal = 25,
                            ProduceCategory = "Vegetable",
                            ProduceDescription = "Organic carrots",
                            ProduceName = "Carrots",
                            UnitPrice = 1.50m
                        },
                        new
                        {
                            ProduceId = 12,
                            InventoryTotal = 12,
                            ProduceCategory = "Fruit",
                            ProduceDescription = "Fresh raspberries",
                            ProduceName = "Raspberries",
                            UnitPrice = 3.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
