// <auto-generated />
using System;
using FreshHarvestMarket.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FreshHarvestMarket.Migrations
{
    [DbContext(typeof(FreshHarvestContext))]
    [Migration("20260424040322_AddUserToOrder")]
    partial class AddUserToOrder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FreshHarvestMarket.Models.Discount", b =>
                {
                    b.Property<int>("DiscountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiscountId"));

                    b.Property<int>("DiscountAmount")
                        .HasColumnType("int");

                    b.Property<int>("ProduceId")
                        .HasColumnType("int");

                    b.HasKey("DiscountId");

                    b.HasIndex("ProduceId")
                        .IsUnique();

                    b.ToTable("Discounts");

                    b.HasData(
                        new
                        {
                            DiscountId = 1,
                            DiscountAmount = 50,
                            ProduceId = 1
                        },
                        new
                        {
                            DiscountId = 2,
                            DiscountAmount = 3,
                            ProduceId = 3
                        });
                });

            modelBuilder.Entity("FreshHarvestMarket.Models.Favorite", b =>
                {
                    b.Property<int>("FavoriteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FavoriteId"));

                    b.Property<int>("ProduceId")
                        .HasColumnType("int");

                    b.HasKey("FavoriteId");

                    b.HasIndex("ProduceId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("FreshHarvestMarket.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<bool>("IsPickedUp")
                        .HasColumnType("bit");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OrderTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PickupDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Rejected")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            IsPickedUp = false,
                            OrderDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderTotal = 12.50m,
                            PickupDate = new DateTime(2026, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rejected = false
                        },
                        new
                        {
                            OrderId = 2,
                            IsPickedUp = false,
                            OrderDate = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderTotal = 22.00m,
                            PickupDate = new DateTime(2026, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rejected = false
                        });
                });

            modelBuilder.Entity("FreshHarvestMarket.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProduceId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProduceId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            OrderItemId = 1,
                            OrderId = 1,
                            ProduceId = 1,
                            Quantity = 3
                        },
                        new
                        {
                            OrderItemId = 2,
                            OrderId = 1,
                            ProduceId = 2,
                            Quantity = 2
                        },
                        new
                        {
                            OrderItemId = 3,
                            OrderId = 2,
                            ProduceId = 3,
                            Quantity = 4
                        });
                });

            modelBuilder.Entity("FreshHarvestMarket.Models.Produce", b =>
                {
                    b.Property<int>("ProduceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProduceId"));

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InventoryTotal")
                        .HasColumnType("int");

                    b.Property<string>("ProduceCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProduceDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProduceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProduceId");

                    b.ToTable("Produce");

                    b.HasData(
                        new
                        {
                            ProduceId = 1,
                            ImageUrl = "zucchini.jpg",
                            InventoryTotal = 20,
                            ProduceCategory = "Vegetable",
                            ProduceDescription = "Fresh green zucchini from Williamsburg, Iowa",
                            ProduceName = "Zucchini",
                            UnitPrice = 1.20m
                        },
                        new
                        {
                            ProduceId = 2,
                            ImageUrl = "tomatoes.jpg",
                            InventoryTotal = 25,
                            ProduceCategory = "Vegetable",
                            ProduceDescription = "Ripe red tomatoes from Victor, Iowa",
                            ProduceName = "Tomatoes",
                            UnitPrice = 2.00m
                        },
                        new
                        {
                            ProduceId = 3,
                            ImageUrl = "honey.jpg",
                            InventoryTotal = 15,
                            ProduceCategory = "Other",
                            ProduceDescription = "Local raw honey from Victor, Iowa",
                            ProduceName = "Honey",
                            UnitPrice = 6.00m
                        },
                        new
                        {
                            ProduceId = 4,
                            ImageUrl = "plums.jpg",
                            InventoryTotal = 18,
                            ProduceCategory = "Fruit",
                            ProduceDescription = "Juicy plums from Amana, Iowa",
                            ProduceName = "Plums",
                            UnitPrice = 2.50m
                        },
                        new
                        {
                            ProduceId = 5,
                            ImageUrl = "potatoes.jpg",
                            InventoryTotal = 30,
                            ProduceCategory = "Vegetable",
                            ProduceDescription = "Freshly harvested potatoes from Ladora, Iowa",
                            ProduceName = "Potatoes",
                            UnitPrice = 1.20m
                        },
                        new
                        {
                            ProduceId = 6,
                            ImageUrl = "blueberries.jpg",
                            InventoryTotal = 12,
                            ProduceCategory = "Fruit",
                            ProduceDescription = "Sweet blueberries from Tiffin, Iowa",
                            ProduceName = "Blueberries",
                            UnitPrice = 3.00m
                        },
                        new
                        {
                            ProduceId = 7,
                            ImageUrl = "sweetcorn.jpg",
                            InventoryTotal = 20,
                            ProduceCategory = "",
                            ProduceDescription = "Fresh sweet corn from Marengo, Iowa",
                            ProduceName = "Sweet Corn",
                            UnitPrice = 1.75m
                        },
                        new
                        {
                            ProduceId = 8,
                            ImageUrl = "broccoli.jpg",
                            InventoryTotal = 15,
                            ProduceCategory = "Vegetable",
                            ProduceDescription = "Green broccoli florets from Millersburg, Iowa",
                            ProduceName = "Broccoli",
                            UnitPrice = 2.25m
                        },
                        new
                        {
                            ProduceId = 9,
                            ImageUrl = "garlic.jpg",
                            InventoryTotal = 40,
                            ProduceCategory = "Vegetable",
                            ProduceDescription = "Fresh garlic bulbs from Montezuma, Iowa",
                            ProduceName = "Garlic",
                            UnitPrice = 0.80m
                        },
                        new
                        {
                            ProduceId = 10,
                            ImageUrl = "cherries.jpg",
                            InventoryTotal = 10,
                            ProduceCategory = "Fruit",
                            ProduceDescription = "Sweet red cherries from Solon, Iowa",
                            ProduceName = "Cherries",
                            UnitPrice = 3.50m
                        },
                        new
                        {
                            ProduceId = 11,
                            ImageUrl = "carrots.jpg",
                            InventoryTotal = 25,
                            ProduceCategory = "Vegetable",
                            ProduceDescription = "Organic carrots from Kalona, Iowa",
                            ProduceName = "Carrots",
                            UnitPrice = 1.50m
                        },
                        new
                        {
                            ProduceId = 12,
                            ImageUrl = "raspberries.jpg",
                            InventoryTotal = 12,
                            ProduceCategory = "Fruit",
                            ProduceDescription = "Fresh raspberries from Swisher, Iowa",
                            ProduceName = "Raspberries",
                            UnitPrice = 3.00m
                        });
                });

            modelBuilder.Entity("FreshHarvestMarket.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FreshHarvestMarket.Models.Discount", b =>
                {
                    b.HasOne("FreshHarvestMarket.Models.Produce", "Produce")
                        .WithOne("Discount")
                        .HasForeignKey("FreshHarvestMarket.Models.Discount", "ProduceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produce");
                });

            modelBuilder.Entity("FreshHarvestMarket.Models.Favorite", b =>
                {
                    b.HasOne("FreshHarvestMarket.Models.Produce", "Produce")
                        .WithMany()
                        .HasForeignKey("ProduceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produce");
                });

            modelBuilder.Entity("FreshHarvestMarket.Models.Order", b =>
                {
                    b.HasOne("FreshHarvestMarket.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FreshHarvestMarket.Models.OrderItem", b =>
                {
                    b.HasOne("FreshHarvestMarket.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FreshHarvestMarket.Models.Produce", "Produce")
                        .WithMany()
                        .HasForeignKey("ProduceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Produce");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FreshHarvestMarket.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FreshHarvestMarket.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FreshHarvestMarket.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FreshHarvestMarket.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FreshHarvestMarket.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("FreshHarvestMarket.Models.Produce", b =>
                {
                    b.Navigation("Discount");
                });
#pragma warning restore 612, 618
        }
    }
}
